spring.application.name=meeting-management
jwt.secret=f9d8a2b4b0f9d0ad89b5c27c8d7d238d2bb2b157bf1c2fa82b3a63d77985ffae
jwt.expiration=3600000
spring.datasource.url=jdbc:mysql://localhost:3306/meeting_management?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=moon
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html




